#pragma once

#define EMULATOR_SHARED_PATH "RVGMEmulator"
#define EMULATOR_PIPE_PATH   EMULATOR_SHARED_PATH"Pipe"
#define EMULATOR_STATUS_PATH EMULATOR_SHARED_PATH"Status"

#define MACHINE_PATH EMULATOR_SHARED_PATH"Machine"

#define DEVICE_PATH EMULATOR_SHARED_PATH"Device"